/*******************************************************************************
 * Size: 20 px
 * Bpp: 4
 * The Claude "spark" mark: a 12-ray sunburst, hand-rasterized (see
 * tools note in git history) rather than generated by lv_font_conv, since no
 * TTF carries this glyph. Mapped to U+E000 (private use). One glyph only.
 ******************************************************************************/

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "lvgl.h"
#endif

#ifndef FONT_CLAUDE
#define FONT_CLAUDE 1
#endif

#if FONT_CLAUDE

/*-----------------
 *    BITMAPS
 *----------------*/

/*Store the image of the glyphs*/
static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    /* U+E000 "" */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x04, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x10,
    0x04, 0x40, 0x01, 0x40, 0x00, 0x00, 0x00, 0x00, 0x01, 0x80, 0x05, 0x50,
    0x08, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x94, 0x08, 0x80, 0x49, 0x00,
    0x00, 0x00, 0x00, 0x41, 0x00, 0x2d, 0x18, 0x81, 0xd2, 0x00, 0x14, 0x00,
    0x00, 0x18, 0x92, 0x09, 0xa8, 0x8a, 0x90, 0x29, 0x81, 0x00, 0x00, 0x00,
    0x4d, 0x94, 0xfe, 0xef, 0x49, 0xd4, 0x00, 0x00, 0x00, 0x00, 0x01, 0xaf,
    0xef, 0xfe, 0xfa, 0x10, 0x00, 0x00, 0x04, 0x45, 0x88, 0x8e, 0xff, 0xff,
    0xe8, 0x88, 0x54, 0x40, 0x04, 0x45, 0x88, 0x8e, 0xff, 0xff, 0xe8, 0x88,
    0x54, 0x40, 0x00, 0x00, 0x01, 0xaf, 0xef, 0xfe, 0xfa, 0x10, 0x00, 0x00,
    0x00, 0x00, 0x4d, 0x94, 0xfe, 0xef, 0x49, 0xd4, 0x00, 0x00, 0x00, 0x18,
    0x92, 0x09, 0xa8, 0x8a, 0x90, 0x29, 0x81, 0x00, 0x00, 0x41, 0x00, 0x2d,
    0x18, 0x81, 0xd2, 0x00, 0x14, 0x00, 0x00, 0x00, 0x00, 0x94, 0x08, 0x80,
    0x49, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x80, 0x05, 0x50, 0x08, 0x10,
    0x00, 0x00, 0x00, 0x00, 0x04, 0x10, 0x04, 0x40, 0x01, 0x40, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x04, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};


/*---------------------
 *  GLYPH DESCRIPTION
 *--------------------*/

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,
    {.bitmap_index = 0, .adv_w = 320, .box_w = 20, .box_h = 20, .ofs_x = 0, .ofs_y = 0}
};

/*---------------------
 *  CHARACTER MAPPING
 *--------------------*/

static const lv_font_fmt_txt_cmap_t cmaps[] =
{
    {
        .range_start = 57344, .range_length = 1, .glyph_id_start = 1,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    }
};

/*--------------------
 *  ALL CUSTOM DATA
 *--------------------*/

#if LVGL_VERSION_MAJOR == 8
/*Store all the custom data of the font*/
static  lv_font_fmt_txt_glyph_cache_t cache;
#endif

#if LVGL_VERSION_MAJOR >= 8
static const lv_font_fmt_txt_dsc_t font_dsc = {
#else
static lv_font_fmt_txt_dsc_t font_dsc = {
#endif
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 4,
    .kern_classes = 0,
    .bitmap_format = 0,
#if LVGL_VERSION_MAJOR == 8
    .cache = &cache
#endif
};



/*-----------------
 *  PUBLIC FONT
 *----------------*/

/*Initialize a public general font descriptor*/
#if LVGL_VERSION_MAJOR >= 8
const lv_font_t font_claude = {
#else
lv_font_t font_claude = {
#endif
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,    /*Function pointer to get glyph's data*/
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,    /*Function pointer to get glyph's bitmap*/
    .line_height = 20,          /*The maximum line height required by the font*/
    .base_line = 0,             /*Baseline measured from the bottom of the line*/
#if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)
    .subpx = LV_FONT_SUBPX_NONE,
#endif
#if LV_VERSION_CHECK(7, 4, 0) || LVGL_VERSION_MAJOR >= 8
    .underline_position = -1,
    .underline_thickness = 1,
#endif
    .dsc = &font_dsc,          /*The custom font data. Will be accessed by `get_glyph_bitmap/dsc` */
#if LV_VERSION_CHECK(8, 2, 0) || LVGL_VERSION_MAJOR >= 9
    .fallback = NULL,
#endif
    .user_data = NULL,
};



#endif /*#if FONT_CLAUDE*/
